/**
 * Cloud sync layer — bridges localStorage cache with Supabase.
 *
 * Strategy:
 *  - Local cache (localStorage) remains the source of truth for UI reads (sync API).
 *  - On login: pull from Supabase to local cache.
 *  - On any write helper here: update local cache + push to Supabase in background.
 *  - First-time login of an existing local-only user: migrates current localStorage data up.
 */

import { supabase } from "@/integrations/supabase/client";
import type { ActiveRoute, RouteEntry, Settings } from "@/lib/storage";
import type { AdditionalExpense } from "@/components/ExtraExpenseForm";

const ROUTES_KEY = "driver_routes";
const SETTINGS_KEY = "driver_settings";
const ACTIVE_ROUTE_KEY = "driver_active_route";
const EXPENSES_KEY = "driver_extra_expenses";
const MIGRATED_FLAG = "driver_cloud_migrated_v1";

let currentUserId: string | null = null;
let pulling = false;
const listeners = new Set<() => void>();

export function onCloudChange(cb: () => void) {
  listeners.add(cb);
  return () => listeners.delete(cb);
}
function emit() {
  listeners.forEach((l) => {
    try { l(); } catch {}
  });
}

export function getCurrentUserId() {
  return currentUserId;
}

/* ---------- Mappers (db row <-> local entity) ---------- */

function rowToRoute(r: any): RouteEntry {
  return {
    id: r.id,
    type: (r.type as any) ?? "route",
    date: r.date,
    kmStart: Number(r.km_start) || 0,
    kmEnd: Number(r.km_end) || 0,
    kmDriven: Number(r.km_driven) || 0,
    dailyValue: Number(r.daily_value) || 0,
    pricePerLiter: Number(r.price_per_liter) || 0,
    avgConsumption: Number(r.avg_consumption) || 0,
    litersUsed: Number(r.liters_used) || 0,
    fuelCost: Number(r.fuel_cost) || 0,
    helperCost: Number(r.helper_cost) || 0,
    fixedFee: Number(r.fixed_fee) || 0,
    reservePerKm: Number(r.reserve_per_km) || 0,
    recommendedReserve: Number(r.recommended_reserve) || 0,
    netProfit: Number(r.net_profit) || 0,
    timeStart: r.time_start ?? "",
    timeEnd: r.time_end ?? "",
    hoursWorked: Number(r.hours_worked) || 0,
    earningsPerHour: Number(r.earnings_per_hour) || 0,
    autoGenerated: !!r.auto_generated,
    platform: r.platform ?? "none",
  };
}

function routeToRow(e: RouteEntry, userId: string) {
  return {
    id: e.id,
    user_id: userId,
    type: e.type ?? "route",
    date: e.date,
    km_start: e.kmStart,
    km_end: e.kmEnd,
    km_driven: e.kmDriven,
    daily_value: e.dailyValue,
    price_per_liter: e.pricePerLiter,
    avg_consumption: e.avgConsumption,
    liters_used: e.litersUsed,
    fuel_cost: e.fuelCost,
    helper_cost: e.helperCost,
    fixed_fee: e.fixedFee,
    reserve_per_km: e.reservePerKm,
    recommended_reserve: e.recommendedReserve,
    net_profit: e.netProfit,
    time_start: e.timeStart ?? "",
    time_end: e.timeEnd ?? "",
    hours_worked: e.hoursWorked,
    earnings_per_hour: e.earningsPerHour,
    auto_generated: !!e.autoGenerated,
    platform: e.platform ?? "none",
  };
}

function rowToSettings(r: any): Settings {
  return {
    avgConsumption: Number(r.avg_consumption) || 0,
    reservePerKm: Number(r.reserve_per_km) || 0,
    helperCost: Number(r.helper_cost) || 0,
    defaultDailyValue: Number(r.default_daily_value) || 0,
    defaultPricePerLiter: Number(r.default_price_per_liter) || 0,
    fixedFee: Number(r.fixed_fee) || 0,
    monthlyGoal: Number(r.monthly_goal) || 0,
    fortnightGoal: Number(r.fortnight_goal) || 0,
    hourlyGoal: Number(r.hourly_goal) || 0,
    routeMode: (r.route_mode as any) ?? "dynamic",
  };
}

function settingsToRow(s: Settings, userId: string) {
  return {
    user_id: userId,
    avg_consumption: s.avgConsumption ?? 0,
    reserve_per_km: s.reservePerKm ?? 0,
    helper_cost: s.helperCost ?? 0,
    default_daily_value: s.defaultDailyValue ?? 0,
    default_price_per_liter: s.defaultPricePerLiter ?? 0,
    fixed_fee: s.fixedFee ?? 0,
    monthly_goal: s.monthlyGoal ?? 0,
    fortnight_goal: s.fortnightGoal ?? 0,
    hourly_goal: s.hourlyGoal ?? 0,
    route_mode: s.routeMode ?? "dynamic",
  };
}

function rowToExpense(r: any): AdditionalExpense {
  return {
    id: r.id,
    date: r.date,
    description: r.description,
    amount: Number(r.amount) || 0,
    category: r.category,
  };
}

function expenseToRow(e: AdditionalExpense, userId: string) {
  return {
    id: e.id,
    user_id: userId,
    date: e.date,
    description: e.description,
    amount: e.amount,
    category: e.category,
  };
}

/* ---------- Pull from cloud ---------- */

async function pullAll(userId: string) {
  if (pulling) return;
  pulling = true;
  try {
    const [routesRes, settingsRes, expensesRes, activeRes, fixedCostsRes] = await Promise.all([
      supabase.from("routes").select("*").eq("user_id", userId).order("date", { ascending: false }),
      supabase.from("settings").select("*").eq("user_id", userId).maybeSingle(),
      supabase.from("extra_expenses").select("*").eq("user_id", userId).order("date", { ascending: false }),
      supabase.from("active_routes").select("*").eq("user_id", userId).maybeSingle(),
      supabase.from("fixed_costs").select("*").eq("user_id", userId).order("created_at", { ascending: true }),
    ]);

    if (routesRes.data) {
      const mapped = routesRes.data.map(rowToRoute);
      localStorage.setItem(ROUTES_KEY, JSON.stringify(mapped));
    }
    if (settingsRes.data) {
      localStorage.setItem(SETTINGS_KEY, JSON.stringify(rowToSettings(settingsRes.data)));
    }
    if (expensesRes.data) {
      localStorage.setItem(EXPENSES_KEY, JSON.stringify(expensesRes.data.map(rowToExpense)));
    }
    if (fixedCostsRes.data) {
      const mapped = fixedCostsRes.data.map((r: any) => ({
        id: r.id,
        name: r.name,
        totalAmount: Number(r.total_amount) || 0,
        period: r.period ?? "monthly",
        perRouteAmount: Number(r.per_route_amount) || 0,
        accumulated: Number(r.accumulated) || 0,
        cycleStart: r.cycle_start,
        active: !!r.active,
      }));
      localStorage.setItem("driver_fixed_costs", JSON.stringify(mapped));
    }
    if (activeRes.data) {
      localStorage.setItem(
        ACTIVE_ROUTE_KEY,
        JSON.stringify({
          startedAt: activeRes.data.started_at,
          kmStart: Number(activeRes.data.km_start),
          helperCost: Number(activeRes.data.helper_cost) || 0,
        } as ActiveRoute)
      );
    } else {
      localStorage.removeItem(ACTIVE_ROUTE_KEY);
    }
    emit();
  } catch (err) {
    console.error("[cloudSync] pull failed", err);
  } finally {
    pulling = false;
  }
}

/* ---------- One-time migration of existing local data ---------- */

async function migrateLocalToCloudIfNeeded(userId: string) {
  if (localStorage.getItem(MIGRATED_FLAG) === userId) return;

  // Only push local data if cloud is empty for this user (avoid duplicating)
  const { count } = await supabase
    .from("routes")
    .select("id", { count: "exact", head: true })
    .eq("user_id", userId);

  if ((count ?? 0) === 0) {
    const localRoutes: RouteEntry[] = JSON.parse(localStorage.getItem(ROUTES_KEY) || "[]");
    const localExpenses: AdditionalExpense[] = JSON.parse(localStorage.getItem(EXPENSES_KEY) || "[]");
    const localSettingsStr = localStorage.getItem(SETTINGS_KEY);
    const localActive = localStorage.getItem(ACTIVE_ROUTE_KEY);

    if (localRoutes.length > 0) {
      const rows = localRoutes.map((r) => routeToRow(r, userId));
      // chunk to avoid payload limits
      for (let i = 0; i < rows.length; i += 200) {
        await supabase.from("routes").upsert(rows.slice(i, i + 200));
      }
    }
    if (localExpenses.length > 0) {
      const rows = localExpenses.map((e) => expenseToRow(e, userId));
      await supabase.from("extra_expenses").upsert(rows);
    }
    if (localSettingsStr) {
      const s: Settings = JSON.parse(localSettingsStr);
      await supabase.from("settings").upsert(settingsToRow(s, userId), { onConflict: "user_id" });
    }
    if (localActive) {
      const a: ActiveRoute = JSON.parse(localActive);
      await supabase.from("active_routes").upsert(
        {
          user_id: userId,
          started_at: a.startedAt,
          km_start: a.kmStart,
          helper_cost: a.helperCost ?? 0,
        },
        { onConflict: "user_id" }
      );
    }
  }

  localStorage.setItem(MIGRATED_FLAG, userId);
}

/* ---------- Init / Auth wiring ---------- */

export function initCloudSync() {
  // Listen to auth state — keep currentUserId fresh and pull on login
  supabase.auth.onAuthStateChange((_event, session) => {
    const newId = session?.user?.id ?? null;
    if (newId !== currentUserId) {
      currentUserId = newId;
      if (newId) {
        // Defer to avoid blocking auth callback
        setTimeout(async () => {
          await migrateLocalToCloudIfNeeded(newId);
          await pullAll(newId);
        }, 0);
      } else {
        // Logout — clear local cache so next user doesn't see it
        localStorage.removeItem(ROUTES_KEY);
        localStorage.removeItem(SETTINGS_KEY);
        localStorage.removeItem(EXPENSES_KEY);
        localStorage.removeItem(ACTIVE_ROUTE_KEY);
        localStorage.removeItem("driver_fixed_costs");
        emit();
      }
    }
  });

  // Immediate session bootstrap
  supabase.auth.getSession().then(async ({ data: { session } }) => {
    const id = session?.user?.id ?? null;
    currentUserId = id;
    if (id) {
      await migrateLocalToCloudIfNeeded(id);
      await pullAll(id);
    }
  });
}

/* ---------- Push helpers (fire-and-forget) ---------- */

function bg<T>(p: PromiseLike<T> | Promise<T>) {
  Promise.resolve(p).catch((err) => console.error("[cloudSync] push failed", err));
}

export function pushRoute(entry: RouteEntry) {
  if (!currentUserId) return;
  bg(supabase.from("routes").upsert(routeToRow(entry, currentUserId)) as any);
}

export function pushDeleteRoute(id: string) {
  if (!currentUserId) return;
  bg(supabase.from("routes").delete().eq("id", id).eq("user_id", currentUserId) as any);
}

export function pushBulkRoutes(entries: RouteEntry[]) {
  if (!currentUserId || entries.length === 0) return;
  bg(supabase.from("routes").upsert(entries.map((e) => routeToRow(e, currentUserId!))) as any);
}

export function pushSettings(s: Settings) {
  if (!currentUserId) return;
  bg(
    supabase
      .from("settings")
      .upsert(settingsToRow(s, currentUserId), { onConflict: "user_id" }) as any
  );
}

export function pushActiveRoute(a: ActiveRoute | null) {
  if (!currentUserId) return;
  if (a) {
    bg(
      supabase
        .from("active_routes")
        .upsert(
          {
            user_id: currentUserId,
            started_at: a.startedAt,
            km_start: a.kmStart,
            helper_cost: a.helperCost ?? 0,
          },
          { onConflict: "user_id" }
        ) as any
    );
  } else {
    bg(supabase.from("active_routes").delete().eq("user_id", currentUserId) as any);
  }
}

export function pushExpense(e: AdditionalExpense) {
  if (!currentUserId) return;
  bg(supabase.from("extra_expenses").upsert(expenseToRow(e, currentUserId)) as any);
}

export function pushDeleteExpense(id: string) {
  if (!currentUserId) return;
  bg(supabase.from("extra_expenses").delete().eq("id", id).eq("user_id", currentUserId) as any);
}
