export type EntryType = "route" | "dayoff";

export interface RouteEntry {
  id: string;
  type?: EntryType; // default: 'route' (backward compat)
  date: string;
  kmStart: number;
  kmEnd: number;
  kmDriven: number;
  dailyValue: number;
  pricePerLiter: number;
  avgConsumption: number;
  litersUsed: number;
  fuelCost: number;
  helperCost: number;
  fixedFee: number;
  reservePerKm: number;
  recommendedReserve: number;
  netProfit: number;
  timeStart: string; // HH:mm
  timeEnd: string;   // HH:mm
  hoursWorked: number;
  earningsPerHour: number;
  autoGenerated?: boolean;
  /** Optional platform tag (e.g. "ifood", "rappi", ...). Defaults to "none" when missing. */
  platform?: string;
}

export interface Settings {
  avgConsumption: number; // km/l
  reservePerKm: number; // R$/km
  helperCost: number; // R$
  defaultDailyValue: number;
  defaultPricePerLiter?: number;
  fixedFee?: number; // R$ per route, optional (default 50)
  monthlyGoal?: number;
  fortnightGoal?: number;
  hourlyGoal?: number;
  routeMode?: "dynamic" | "manual";
}

export interface ActiveRoute {
  startedAt: string; // ISO
  kmStart: number;
  helperCost: number; // 0 if no helper
}

const ROUTES_KEY = "driver_routes";
const SETTINGS_KEY = "driver_settings";
const ACTIVE_ROUTE_KEY = "driver_active_route";
const LAST_OPEN_KEY = "driver_last_open";

export function getRoutes(): RouteEntry[] {
  const data = localStorage.getItem(ROUTES_KEY);
  return data ? JSON.parse(data) : [];
}

export function saveRoute(entry: RouteEntry) {
  const routes = getRoutes();
  routes.unshift(entry);
  localStorage.setItem(ROUTES_KEY, JSON.stringify(routes));
}

export function deleteRoute(id: string) {
  const routes = getRoutes().filter((r) => r.id !== id);
  localStorage.setItem(ROUTES_KEY, JSON.stringify(routes));
}

export function getSettings(): Settings {
  const data = localStorage.getItem(SETTINGS_KEY);
  if (!data) return {
    avgConsumption: 10,
    reservePerKm: 0.10,
    defaultDailyValue: 350,
    helperCost: 50,
    defaultPricePerLiter: 6.0,
    fixedFee: 50,
    monthlyGoal: 0,
    fortnightGoal: 0,
    hourlyGoal: 0,
    routeMode: "dynamic",
  };
  const parsed = JSON.parse(data);
  return {
    monthlyGoal: 0,
    fortnightGoal: 0,
    hourlyGoal: 0,
    defaultPricePerLiter: 6.0,
    fixedFee: 50,
    routeMode: "dynamic",
    ...parsed,
  };
}

export function saveSettings(settings: Settings) {
  localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
}

/** Active route helpers */
export function getActiveRoute(): ActiveRoute | null {
  const data = localStorage.getItem(ACTIVE_ROUTE_KEY);
  return data ? JSON.parse(data) : null;
}
export function setActiveRoute(r: ActiveRoute | null) {
  if (r) localStorage.setItem(ACTIVE_ROUTE_KEY, JSON.stringify(r));
  else localStorage.removeItem(ACTIVE_ROUTE_KEY);
}

/** Filter routes only (no dayoff entries) for calculations */
export function onlyRoutes(routes: RouteEntry[]): RouteEntry[] {
  return routes.filter((r) => (r.type ?? "route") === "route");
}

export function calculateEntry(
  date: string,
  kmStart: number,
  kmEnd: number,
  dailyValue: number,
  pricePerLiter: number,
  timeStart: string,
  timeEnd: string,
  helperCostOverride?: number,
  platform?: string,
): RouteEntry {
  const settings = getSettings();
  const kmDriven = kmEnd - kmStart;
  const avgConsumption = settings.avgConsumption;
  const litersUsed = kmDriven / avgConsumption;
  const fuelCost = litersUsed * pricePerLiter;
  const fixedFee = settings.fixedFee ?? 50;
  const reservePerKm = settings.reservePerKm;
  const recommendedReserve = reservePerKm * kmDriven;
  const isExempt = dailyValue < 350;
  const actualFixedFee = isExempt ? 0 : fixedFee;
  const baseHelper = helperCostOverride ?? settings.helperCost;
  const actualHelperCost = isExempt ? 0 : baseHelper;
  const netProfit = dailyValue - fuelCost - actualHelperCost - actualFixedFee;

  const [sh, sm] = timeStart.split(":").map(Number);
  const [eh, em] = timeEnd.split(":").map(Number);
  let hoursWorked = (eh + em / 60) - (sh + sm / 60);
  if (hoursWorked < 0) hoursWorked += 24;
  const earningsPerHour = hoursWorked > 0 ? netProfit / hoursWorked : 0;

  return {
    id: crypto.randomUUID(),
    type: "route",
    date,
    kmStart,
    kmEnd,
    kmDriven,
    dailyValue,
    pricePerLiter,
    avgConsumption,
    litersUsed,
    fuelCost,
    helperCost: actualHelperCost,
    fixedFee: actualFixedFee,
    reservePerKm,
    recommendedReserve,
    netProfit,
    timeStart,
    timeEnd,
    hoursWorked,
    earningsPerHour,
    platform: platform ?? "none",
  };
}

/** Build a dayoff entry */
export function makeDayOff(date: string): RouteEntry {
  return {
    id: crypto.randomUUID(),
    type: "dayoff",
    date,
    kmStart: 0, kmEnd: 0, kmDriven: 0,
    dailyValue: 0, pricePerLiter: 0, avgConsumption: 0,
    litersUsed: 0, fuelCost: 0, helperCost: 0, fixedFee: 0,
    reservePerKm: 0, recommendedReserve: 0, netProfit: 0,
    timeStart: "", timeEnd: "", hoursWorked: 0, earningsPerHour: 0,
    autoGenerated: true,
  };
}

/**
 * Detect missing days between last entry and yesterday and insert dayoff entries.
 * Only runs once per app open (tracked by LAST_OPEN_KEY).
 */
export function ensureAutoDayOffs() {
  const today = new Date();
  const todayStr = formatDate(today);
  const lastOpen = localStorage.getItem(LAST_OPEN_KEY);
  if (lastOpen === todayStr) return;

  const routes = getRoutes();
  // Most recent entry date (any type)
  const sorted = [...routes].sort((a, b) => (a.date < b.date ? 1 : -1));
  const lastDate = sorted[0]?.date;
  if (!lastDate) {
    localStorage.setItem(LAST_OPEN_KEY, todayStr);
    return;
  }

  const start = new Date(lastDate + "T00:00:00");
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);

  const existing = new Set(routes.map((r) => r.date));
  const toAdd: RouteEntry[] = [];
  const cursor = new Date(start);
  cursor.setDate(cursor.getDate() + 1);
  while (cursor <= yesterday) {
    const ds = formatDate(cursor);
    if (!existing.has(ds)) toAdd.push(makeDayOff(ds));
    cursor.setDate(cursor.getDate() + 1);
  }

  if (toAdd.length) {
    const merged = [...toAdd, ...routes].sort((a, b) => (a.date < b.date ? 1 : -1));
    localStorage.setItem(ROUTES_KEY, JSON.stringify(merged));
  }
  localStorage.setItem(LAST_OPEN_KEY, todayStr);
}

function formatDate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export function exportToCSV(routes: RouteEntry[]) {
  const real = onlyRoutes(routes);
  const headers = [
    "Data","Início","Fim","Horas","KM Inicial","KM Final","KM Rodados",
    "Faturamento","Preço/Litro","Consumo Médio (km/l)","Litros Usados",
    "Custo Combustível","Custo Ajudante","Taxa Fixa","Reserva Recomendada","Lucro Real","R$/Hora",
  ];
  const rows = real.map((r) => [
    r.date, r.timeStart || "", r.timeEnd || "", (r.hoursWorked || 0).toFixed(1),
    r.kmStart, r.kmEnd, r.kmDriven, r.dailyValue.toFixed(2), r.pricePerLiter.toFixed(2),
    r.avgConsumption.toFixed(1), r.litersUsed.toFixed(2), r.fuelCost.toFixed(2),
    r.helperCost.toFixed(2), r.fixedFee.toFixed(2), r.recommendedReserve.toFixed(2),
    r.netProfit.toFixed(2), (r.earningsPerHour || 0).toFixed(2),
  ]);
  const csv = [headers.join(";"), ...rows.map((r) => r.join(";"))].join("\n");
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `rotas_${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
